version: '3.8'

services:
  skillbox-backend:
    image: ghcr.io/carstenrossi/skillbox-backend:20250614-225724
    ports:
      - "3001:3001"  # Backend muss einen Port exposen für Reverse Proxy
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0  # Wichtig: Auf alle Interfaces binden
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=https://skillboxdocker2-u31060.vm.elestio.app,http://localhost:3000,http://localhost:3003
      - CORS_CREDENTIALS=true
    volumes:
      - backend_data:/app/data
      - backend_logs:/app/logs
    restart: unless-stopped
    # Removed user specification to avoid permission issues
    networks:
      - skillbox-network

  skillbox-frontend:
    image: ghcr.io/carstenrossi/skillbox-frontend:20250614-225724
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - frontend_logs:/var/log/nginx
    restart: unless-stopped
    # Removed user specification to avoid permission issues  
    networks:
      - skillbox-network
    depends_on:
      - skillbox-backend

volumes:
  backend_data:
  backend_logs:
  frontend_logs:

networks:
  skillbox-network:
    driver: bridge 